import { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Header from "@/shared/Header/Header.component";

export const metadata: Metadata = {
  title: "Finanzapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div className="flex flex-col min-h-screen mx-auto">
          <div className="flex-grow">
            <main className="flex flex-col items-center justify-center">
              <Providers>{children}</Providers>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
