import { fetchDolarOficial } from "@/services/api.dolar";
import { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Header from "@/shared/components/Header/Header.component";

export const metadata: Metadata = {
  title: "Finanzapp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let dolarRate = 1;
  try {
    const dolar = await fetchDolarOficial();
    dolarRate = dolar.venta;
  } catch {
    // fallback: currency toggle still works, USD shows ARS values
  }

  return (
    <html lang="en">
      <body>
        <Providers dolarRate={dolarRate}>
          <Header />
          <div className="flex flex-col min-h-screen">
            <div className="flex-grow">
              <main className="flex flex-col w-full">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
